services:
  odoo_web :
    image: odoo:18.0
    depends_on:
      - postdb
    ports:
      - "8080:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=postdb
      - USER=odoo
      - PASSWORD=myodoo
    networks:
      - odoo_network
  postdb:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo_network

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  odoo_network: